name: globaltechnologie_app
description: "Application Flutter pour la vente de produits et la formation professionnelle."
publish_to: 'none'

version: 1.5.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.15
  image_picker: ^1.0.4
  http: ^1.1.0
  font_awesome_flutter: ^10.4.0  # ✅ pour les icônes Google et Facebook

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_tech.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/ordinateur.png
    - assets/circuit.png
    - assets/chargeur.png
    - assets/batterie.png
    - assets/panneau.png
    - assets/cable.png
    - assets/structure.json

dependency_overrides:
  characters: ^1.4.1
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7
  vector_math: ^2.2.0
  vm_service: ^15.0.2
